### PR TITLE
Open files by extension #168

### PR DESCRIPTION
**Pull request by FrozenAssassine**

### CODE REVIEW

**Comment by FrozenAssassine** [comment]
What do you think about my latest commit, I tried to clean up the database, because I ran into many issues. 
The biggest was the missing function for checking whether the entered password is correct. So I just wanted to add this, but this resulted in more problems. So I kind of changed the whole database.

I tested and everything should work as expected, but now there is DatabaseItem and Database. 
DatabaseItem handles all the single database specific stuff and Database handles everything for all items or static functions stuff.

Pleeease @finn-freitag and @Flamifly have a look at my code if possible. I don't want to break everything when merging🤞 

REF: #173

**Comment by Flamifly** [comment]
I will take a Look in an hour or two

**Comment by FrozenAssassine** [comment]
Perfect, thank you very much, always better to have someone else looking👍

**Comment by Flamifly** [comment]
It will take a little bit longer before I can take a look on your changes I am watching a movie rn but after it I will check it.
Hope it's fine

**Comment by FrozenAssassine** [comment]
No problem, I am doing the same rn, have fun 😂✌️

**Comment by Flamifly** [comment]
Thanks you too

**Comment by Flamifly** [comment]
So it works. Good Job👍

So the first thing I would say at the moment is that I would change the Button translation
image
It should be something like "Save Temp Database" in my opinion
A Tooltip could be "Saves the Temporary Database to your Password Manager"

**Comment by Flamifly** [comment]
I will take a look on the code now

**Comment by FrozenAssassine** [comment]
Oh yeah the translations are pretty bad haha. They are also not translated yet.

**Comment by Flamifly** [comment]
The code looks fine small performance improvements but still good
If I get it right you splitted the Database.cs into 2/3 Classes right?

**Comment by FrozenAssassine** [comment]
Exactly I splitted into 3 classes, one handles backwards compatibility, the other handles the individual database items and the last one handles more like helper and tool functions

**Comment by FrozenAssassine** [comment]
Ok I will merge then and the translations and localization can be fixed directly then

**Pull request merged**
