### PR TITLE
Performance Improve Password Generator

### PR DESCRIPTION
**Pull request by Flamifly**
I reduced the amount of Web Request for the Password Generator
If we generated a Password that has been leaked we should create a new one
This will be achieved by adding an additional Loop which checks at the end of the Password generation if it was leaked

### CODE REVIEW

**Comment by Flamifly** [comment]
forgot clearing the Password (fixed now)
- No Compilation errors
- Password Generator does not throw errors
- Password Generator result looks fine to me

**Comment by FrozenAssassine** [comment]
But wouldn't a one time for loop be smarter instead of all those .Any linq functions?

**Comment by Flamifly** [comment]
Yea but tbh that's something we do not have to concern about for now because this takes ns.
I Benchmarked it and it took 50us (Don't know what exactly us is)
image

Tested with a Password with a Length of 12

**Comment by FrozenAssassine** [comment]
Ok perfect, then there is no need.

1 second is 1 000 000 µs
1 second is 1 000 000 000 ns

So ns is way faster than µs if I am correct

**Pull request merged**
