### PR TITLE
Adding/Chaning Translations for #133 and Fixed #156 in addition added Info Messages

### LINKED ISSUE #156: Create Database Dialog does not show Error
If I want to create a new Database the Dialog does not tell me that I have two different Passwords if I click on create
image

### PR DESCRIPTION
**Pull request by Flamifly**
I tested the InfoMessages on the CreateDatabase and ChangePassword Dialog (worked and no errors occured)
I tested the Translations on the PasswordChart (worked no errors occured)
No Compilation errors

### CODE REVIEW

**Comment by Flamifly** [comment]
Need to test it before merge

**Comment by FrozenAssassine** [comment]
Good job, ready to merge?

**Comment by Flamifly** [comment]
tested it
- fixed: resw File because before you could not compile anymore
- added: correct translations for #133 

Works now

**Comment by FrozenAssassine** [comment]
Ok, then I can merge?

**Comment by Flamifly** [comment]
Wait I tripple check

**Comment by Flamifly** [comment]
Yes it works

**Pull request merged**
