### PR TITLE
Remove duplicate implementations #147

### PR DESCRIPTION
**Pull request by FrozenAssassine**

### CODE REVIEW

**Comment by FrozenAssassine** [comment]
@Flamifly What do you think about my changes, is it better or do you have more to improve here?

**Review by finn-freitag — APPROVED** [review]

**Comment by Flamifly** [comment]
It's way better than bevor good job👍

But there is one more thing you could do
You do twice a null check and set the value to "" if true.
You could pass the string as ref and set it once in the Method but you don't have to do that change

**Comment by Flamifly** [comment]
I will take a deeper Look in the evening but at the Moment I would say it looks good

**Comment by FrozenAssassine** [comment]
Awesome, I'll let this PR open so you can commit your changes👍

**Comment by Flamifly** [comment]
You can merge theres nothing I would change at the moment
There could be some small performance improvements with spans but I can do that some other day

**Pull request merged**
