### PR TITLE
Small Performance improve, undo previous change (length local var), adding File Helper

### PR DESCRIPTION
**Pull request by Flamifly**
x

### CODE REVIEW

**Comment by FrozenAssassine** [comment]
Good job, do you want to merge or should I wait?

**Comment by Flamifly** [comment]
I changed the code at some places to the coding guidlines
You can merge if everything looks good

I will now change the Translations for the PasswordChart

**Comment by FrozenAssassine** [comment]
Did you forget to push something, because I now get some errors, or did you rename something and now it is incorrect 😂?
I think it is looking for File.

image

**Comment by Flamifly** [comment]
No I did not forgot these changes 😂
The first name was File I changed it to FileHelper but it changed every File to FileHelper I saw rn 😂
My bad
Good that you noticed cause I saw it just now

**Pull request merged**
